- docs/tutorial/DataFrame.ipynb
Hi, thanks for the great OSS and documentation. 
I found a small typo in the documentation and have fixed it.
> docs: fix typo

- DEPLOYMENT.md
> 修改集群SPU配置文档错误

- INSTALLATION.md
add how to install secretflow on windows by WSL so that a windows user can try or use  secretflow.
> add WSL to use secretflow in windows

- .circleci/config.yml
> Add ci timer

- secretflow/device/device/spu.py
> Update spu.py, fix issue 282

- secretflow/device/driver.py
I asked on #290 and got a very good answer so I submit this PR that I thought it should be in the document. Thank you!
> Add docs for wait, closes #290

- secretflow/ml/nn/sl/backend/tensorflow/strategy/__init__.py
- secretflow/ml/nn/sl/sl_model.py
- setup.py
Add `__init__.py` in `secretflow/ml/nn/sl/backend/tensorflow/strategy` to fix #310
> Add __init__.py in sl tensorflow strategy folder

- CHANGELOG.md
- requirements.txt
- secretflow/device/driver.py
- setup.py
Bump to 0.7.18b4
- Fix min num_cpus for simulation.
- Bump RayFed to 0.1.1a0 to fix some bugs.
> feat: 0.7.18b4 for some fixs.

- CHANGELOG.md
- docker/release/anolis.Dockerfile
- docker/release/build.sh
- docker/release/environment.yml
- docker/release/python.Dockerfile
- requirements.txt
- secretflow/device/link.py
- setup.py
Upgrade dependencies for security fix and minimize release docker.
> feat: bump dependencies for security fix.

- CHANGELOG.md
- requirements.txt
- secretflow/device/device/spu.py
- setup.py
- tests/basecase.py
- tests/device/test_psi.py
> feat: introduce SCQL.

- secretflow/__init__.py
- secretflow/version.py
- setup.py
> Add version.py

- README.md
- README.zh-CN.md
> fix: correct link in readme.

- docs/locales/zh_CN/LC_MESSAGES/tutorial/Split_Learning_for_bank_marketing.po
resolve https://github.com/secretflow/secretflow/issues/444
> fix:translation error in the doc of the chinese version

- CHANGELOG.md
- docs/developer/design/teeu.md
- docs/locales/zh_CN/LC_MESSAGES/developer/design/teeu.po
- docs/locales/zh_CN/LC_MESSAGES/tutorial/teeu.po
- docs/locales/zh_CN/LC_MESSAGES/tutorial/teeu_xgboost.po
- docs/tutorial/teeu.md
- docs/tutorial/teeu_xgboost.md
- secretflow/__init__.py
- secretflow/device/device/teeu.py
- secretflow/version.py
> fix: teeu function serialization protocol and docs.

- docker/release/anolis.Dockerfile
- docker/release/anolis_entrypoint.py
- docker/release/anolis_entrypoint.sh
feat:add a welcome message and show some necessary information of version when the container starts
> add a welcome message and show some necessary  information in container

- docs/awesome-pets/awesome-pets.md
- docs/awesome-pets/papers/applications/set/psi.md
Add a new EuroCrypt20 paper: PSI from PaXoS: Fast, Malicious Private Set Intersection. This paper first used a new data structure, called a probe-and-XOR of strings(PaXoS) in PSI.
> Add new paper for awesome-pets/psi

- docs/locales/zh_CN/LC_MESSAGES/tutorial/teeu.po
- docs/locales/zh_CN/LC_MESSAGES/tutorial/teeu_xgboost.po
- docs/tutorial/teeu.md
- docs/tutorial/teeu_xgboost.md
> docs: fix teeu.

- docs/getting_started/deployment.md
- docs/locales/zh_CN/LC_MESSAGES/getting_started/deployment.po
I add IP white list document guide to avoid disabling the firewall of the host to resolve and avoid https://github.com/secretflow/secretflow/issues/527
> doc-fix:add IP white list document guide to avoid disabling the firewall of the host

- docs/locales/zh_CN/LC_MESSAGES/tutorial/GPU_check.po
- docs/tutorial/GPU_check.ipynb
Add lr demo to check jax and update GPU_check.ipynb
> Add lr demo to check jax and update GPU_check.ipynb

- docs/awesome-pets/awesome-pets.md
- docs/awesome-pets/papers/applications/aml/attack_defense.md
Add four new papers:  
- [Gradient Inversion with Generative Image Prior. NeurIPS 2021.](https://arxiv.org/pdf/2110.14962.pdf)
- [Evaluating Gradient Inversion Attacks and Defenses in Federated Learning. NeurIPS 2021.](https://arxiv.org/pdf/2112.00059.pdf)
- [Comprehensive Privacy Analysis of Deep Learning: Passive and Active White-box Inference Attacks against Centralized and Federated Learning. S&P 2019.](https://arxiv.org/pdf/1812.00910.pdf)
- [Label Inference Attacks Against Vertical Federated Learning. USENIX Security 2022.](https://www.usenix.org/system/files/sec22-fu-chong.pdf)
Fix two format problems:
- iDLG display error
- removed one duplicate paper: [Inverting Gradients - …
> Add new paper for awesome-pets/aml

- docs/getting_started/deployment.md
- docs/locales/zh_CN/LC_MESSAGES/getting_started/deployment.po
I add document guide to deploy SecretFlow in WSL(Windows Subsystem for Linux) with simulation mode
> Add deploy SecretFlow in WSL(Windows Subsystem for Linux) with simulation mode

- docs/awesome-pets/awesome-pets.md
- docs/awesome-pets/papers/tools/mpc.md
- docs/awesome-pets/papers/tools/zkp.md
> In this PR, I tried to add more malicious security and zkp-based protocols in MPC.
In offline techniques, I tried to add a new H3 title named "preprocessing", which includes several preprocessing techniques. For example, daBit (double authenticated Bit), EdaBit (Extended Dabit), beaver triple generation by using cut-and-choose. They correspond to three papers.
- MArBled Circuits: Mixing Arithmetic and Boolean Circuits with Active Security. This paper introduces a new technique called "daBit" which can be used in many functionalities, such as share conversion, comparison, etc.
- Improved primitives for MPC over mixed arithmetic-binary circuits. This paper improves edaBit and introduces "Extended" edaBit to make better performance.
- High-Throughput …
> add more malicious security and zkp-based protocol

- docs/awesome-pets/papers/tools/mpc.md
Add CCS 2020 paper Ferret COT, which is a fast and widely used COT protocol.
> Add new paper for awesome-pets/mpc

- docs/awesome-pets/papers/tools/mpc.md
Remove ZKP category since combining ZKP with MPC usually deals with the issue against malicious parties
> Remove MPC/ZKP category

- docs/awesome-pets/papers/tools/he.md
> he init & add papers by @xfap & @liang-xiaojian

- secretflow/ml/linear/fl_lr_mix.py
- secretflow/ml/linear/interconnection/router_hooks.py
- tests/ml/linear/test_fl_lr_mix.py
base code for HuaKong interconnection
> PullRequest: 769 base code for HuaKong interconnection

- docs/awesome-pets/tutorials/talks.md
Update document: add video link of meetup@shenzhen
> add video link of meetup@shenzhen

- docs/getting_started/installation.md
Based the GPU docker images,I updated the installation.md.
Please review the  installation.md; when the English content are accepted, I follow [documentation-update-and-its-multilingual-version](https://github.com/secretflow/secretflow/blob/main/CONTRIBUTING.md#documentation-update-and-its-multilingual-version) supply the Chinese version of document.
> Based the GPU docker images,update the document.

- docs/awesome-pets/papers/applications/set/psi.md
Their study the problem of private set-intersection in the multi-party setting and design two protocols with the following improvements compared to prior work. First, Their protocols are designed in the so-called star network topology, where a designated party communicates with everyone else, and take a new approach of leveraging the 2PC protocol. This approach minimizes the usage of a broadcast channel, where our semi-honest protocol does not make any use of such a channel and all communication is via point-to-point channels.In addition, the communication complexity of our protocols scales with the number of parties.
> feat: Update psi.md

- docs/locales/zh_CN/LC_MESSAGES/components/mpc_ml/linear_model.po
resolve  https://github.com/secretflow/secretflow/issues/489
> Replace link of wikipedia with link of d2l.ai

- docs/locales/zh_CN/LC_MESSAGES/getting_started/installation.po
Based the updating of the document(https://github.com/secretflow/secretflow/pull/626),  update the Chinese version of the document.
> Add Chinese version of installation.md

- docs/awesome-pets/papers/applications/set/pir.md
Paper: SPG: Structure-Private Graph Database via SqueezePIR, VLDB 2023 in Yuan Xie Group
[ This paper presents SPG,  a structure-private graph database with SqueezePIR.  SPG is  built on top of Private Information Retrieval (PIR), which securely  hides which nodes/neighbors are accessed.  In addition, this paper propose SqueezePIR, a compression technique to overcome the computation  overhead of PIR.  Based on evaluation, SqueezePIR achieves 11.85× speedup on average with less than 2% accuracy loss when  compared to the state-of-the-art FastPIR protocol]
> Add new papers

- docs/locales/zh_CN/LC_MESSAGES/components/mpc_ml/decision_tree.po
- docs/locales/zh_CN/LC_MESSAGES/components/mpc_ml/feature_eng.po
documents validation https://github.com/secretflow/secretflow/issues/640
> typo fixed

- CONTRIBUTING.md
Based the experience of updating of the document, update the steps to update the document.
> Update steps of contributing of document

- docs/tutorial/Split_Learning_for_bank_marketing.ipynb
fix https://github.com/secretflow/secretflow/pull/663
> fix sl bank format

- CONTRIBUTING.md
> doc:fix documnet duplicate error

- requirements.txt
> fix: specify jax&jaxlib version as jax has incompatible upgrade.

- docs/awesome-pets/papers/applications/ppml/fl/application.md
This is the first benchmark paper for FL plus audio with both clean and noisy data.  The paper has been accepted to ICASSP 2023.
> Add FedAudio to application.md

- secretflow/ml/nn/sl/backend/torch/sl_base.py
- secretflow/ml/nn/sl/sl_model.py
- Fix training dataset evaluation & validation dataset evaluation bug when the scoring function returns tensors of shape [batch_size, 1], which are crucial in binary prediction tasks with metrics like AUROC
- Change the default behavior of parameter ``audit_log_dir`` in ``SLModel.fit``, since by default loading from intermediate checkpoints may encounter unintended behaviors.
> Fix torch SL bug on model training and evaluation

- requirements.txt
- secretflow/version.py
Bump rayfed, related PR https://github.com/secretflow/rayfed/pull/1
> feat: bump rayfed to 0.1.1a4.

- docs/awesome-pets/papers/tools/zkp.md
fined the application category of zkp
fix some markdown format errors
rm some unpublished papers
> fined zkp application & fix format

- examples/README.md
- examples/app/h_aigc/README.md
- examples/app/h_audio/README.md
- examples/app/h_cv/README.md
- examples/app/h_gnn/README.md
- examples/app/h_llm/README.md
- examples/app/h_nlp/README.md
- examples/app/v_gnn/README.md
- examples/app/v_recommendation/README.md
- examples/app/v_recommendation/deep_fm/data/dataset.py
- examples/app/v_recommendation/deep_fm/deepfm_simulation.py
- examples/app/v_recommendation/deep_fm/model/deepfm_model.py
- examples/security/v_eva/README.md
- examples/security/v_fia/README.md
- examples/security/v_lia/README.md
- examples/security/v_mia/README.md
- examples/security/v_tpa/README.md
- examples/security/v_upa/README.md
- secretflow/utils/simulation/datasets.py
> refactor: examples folders init

- docs/locales/zh_CN/LC_MESSAGES/tutorial/CustomDataLoaderTF.po
- docs/tutorial/CustomDataLoaderTF.ipynb
#700 
将 SecretFlow《[在 SecretFlow 中使用自定义 DataBuilder（Tensorflow）]》中文文档逐句翻译成英文文档
1. 翻译过程中发现原中文文档有部分错误，如下
flower数据集是一个包含了5种花卉（郁金香、黄水仙、鸢尾花、百合、向日葵）
应修改为: 
flower数据集是一个包含了5种花卉（雏菊、蒲公英、玫瑰、向日葵、郁金香）
为了保持一致，我没有对原本的中文文档进行修改
2. 完成翻译后的英文文档预览页面截图：
> translate chinese to english

- docs/locales/zh_CN/LC_MESSAGES/tutorial/FedNdarrayDataLoader.po
- docs/tutorial/FedNdarrayDataLoader.ipynb
update the docs, FedNdarrayDataLoader.ipynb and FedNdarrayDataLoader.po
> update the FedNdarrayDataLoader.ipynb and FedNdarrayDataLoader.po

- docs/awesome-pets/papers/tools/mpc.md
Add OT/VOLE papers  
- baseOT: [BM89] && [NP01]  
- VOLE: Wolverine && Moz$`\mathbb{Z}_{2^k}`$ arella
> Update mpc papers

- secretflow/ml/nn/sl/agglayer/agg_layer.py
- secretflow/ml/nn/sl/backend/torch/sl_base.py
- secretflow/utils/compressor.py
> add compression in agg_layer.

- docs/awesome-pets/tutorials/talks.md
I add video link of meetup of one year anniversary and oscp.
> docs:add video link of meetup of one year anniversary and oscp

- docs/awesome-pets/papers/applications/ppml/fl/vertical.md
KDD'20: [Federated Doubly Stochastic Kernel Learning for Vertically Partitioned Data] A novel model combining kernel with model training by using random feature, faster training and convergence.
[Privacy preserving vertical federated learning for tree-based models] For tree model in VFL without a third party, can be used for GBDT.
KDD'21: [When Homomorphic Encryption Marries Secret Sharing: Secure Large-Scale Sparse Logistic Regression and Applications in Risk Control] Combine HE and SS to avoid Beaver triplet and speed up a lot for high-dimensional sparse data.
IEEE transaction: [FedBCD: A Communication-Efficient Collaborative Learning Framework for Distributed Features] decreasing …
> Add new papers (Remove one of the non-compliant references).

- README.md
- docs/developer/design/architecture.md
- docs/getting_started/deployment.md
- docs/index.rst
- docs/locales/zh_CN/LC_MESSAGES/developer/design/architecture.po
- docs/locales/zh_CN/LC_MESSAGES/getting_started/deployment.po
- docs/locales/zh_CN/LC_MESSAGES/index.po
> Use "privacy-preserving computing" everywhere

- docs/awesome-pets/papers/applications/set/psi.md
- docs/awesome-pets/papers/tools/mpc.md
在MPC中提交的两篇都是关于从半诚实安全mpc到公开可验证covert安全的mpc编译器
在PSI中提交的一篇关于具有线性通信复杂度的电路PSI论文
> Publicly Verifiable Covert MPC & Circuit-PSI

- docs/awesome-pets/papers/applications/set/psi.md
Add a new paper：Structure-Aware Private Set Intersection with Applications to Fuzzy matching.
It introduce new generic paradigm for structrue-aware Psi based on function secret-sharing(FSS) which improve the performance when one of the party's data strucutre is public known.  And  it develop several improved FSS techniques and explore Sa-PSI in depth a natural application of it, such as Fuzzy matching.
> add new paper

- docs/awesome-pets/papers/tools/zkp.md
> fix category name

- docs/locales/zh_CN/LC_MESSAGES/tutorial/CustomDataLoaderOnSL.po
- docs/locales/zh_CN/LC_MESSAGES/tutorial/CustomDataLoaderTF.po
- docs/locales/zh_CN/LC_MESSAGES/tutorial/CustomDataLoaderTorch.po
- docs/tutorial/CustomDataLoaderOnSL.ipynb
- docs/tutorial/CustomDataLoaderTorch.ipynb
Restore i18n changes from #854
> fix(i18n): restore #854

- docs/awesome-pets/papers/applications/ppml/sl/attack.md
- docs/awesome-pets/papers/applications/ppml/sl/defense.md
- docs/awesome-pets/papers/applications/ppml/sl/introduction_and_application.md
- docs/awesome-pets/papers/applications/ppml/sl/split_learning.md
Split Learning, which is also an improtant aspect, is considerd a solution for machine learning privacy that takes place between clients and servers. So I add some papers about the introduction and applications of Split Learning. Meanwhile, there are some works about the security of Split Learning, so I add these works categorized by Attacks and Defenses. Also I make new directory according to the category.
> Add papers about Split Learning

- docs/getting_started/deployment.md
错别字修改，这里应该是bob的集群已经启动
---
---
---
> Update deployment.md 错别字修改

- docs/awesome-pets/papers/applications/ppml/ppml_crypto.md
- When Machine Learning Meets Privacy: A Survey and Outlook: This paper considered different roles of machine learning and discussed privacy-preserving ML, ML-aided privacy protection, ML-based attacks.  Besides, this number of citing of this paper at Google Scholar is 282.
- Privacy-Preserving Machine Learning: Methods, Challenges and Directions: This paper summarized the unique characteristics and challenges in privacy-preserving machine learning. They proposed phase, guarantee and utility triad based model to understand various solutions. While this paper is a preprint paper, this number of citing of this paper at Google Scholar is 49.
> docs: add two high-cited survey on ppml

- docs/awesome-pets/awesome-pets.md
- docs/awesome-pets/papers/tools/mpc.md
This book introduces several important MPC protocols, and surveys methods for improving the efficiency of privacy-preserving applications built using MPC. Besides giving a broad overview of the field and the insights of the main constructions, this book overviews the most currently active areas of MPC research and aim to give readers insights into what problems are practically solvable using MPC today and how different threat models and assumptions impact the practicality of different approaches.
> Docs: add a book about MPC to awesome-pets

- docs/locales/zh_CN/LC_MESSAGES/developer/design/architecture.po
> [Update architecture.po]Substitute SPU for PPU

- docs/locales/zh_CN/LC_MESSAGES/user_guide/preprocessing/DataFrame.po
> docs: fixed translation errors

- docs/awesome-pets/papers/applications/ppml/fl/application.md
This is the first benchmark paper focusing on federated learning for multimodal learning. The paper includes various types of datasets and addresses several real-world application challenges such as missing modality, missing labels, and label errors. The paper has been accepted by KDD 2023.
> add FedMultimodal into application

- docs/tutorial/teeu_xgboost.md
> docs: fix xgboost teeu demo code.

- secretflow/security/aggregation/experiment/ppb_aggregator.py
- tests/security/aggregation/test_ppb_aggregator.py
> [OSCP][ppb_aggregator]联邦学习中的安全聚合方案设计及实现

- docs/tutorial/Custom_Loss_Federated_Learning_with_Pytorch.ipynb
Fixed https://github.com/secretflow/secretflow/issues/1044
> 【OSCP】在 SecretFlow 中提供自定义 loss function 的教程

- secretflow/ml/nn/experimental/README.md
- secretflow/ml/nn/experimental/__init__.py
- secretflow/ml/nn/experimental/fl/__init__.py
- secretflow/ml/nn/experimental/fl/backend/tensorflow/strategy/__init__.py
- secretflow/ml/nn/experimental/fl/backend/torch/__init__.py
- secretflow/ml/nn/experimental/fl/backend/torch/strategy/__init__.py
- secretflow/ml/nn/experimental/sl/__init__.py
add experimental forder,  helping committer to commit code pending correctness validation.
> [refactor]add experimental folder for nn

- docs/tutorial/teeu_xgboost.md
[Bug fix]：
1. alice&bob is not defined
2. missing bob's use of gen_data()
3. Replace python3.8 with python, the same as teeu.md
---
---
--- …
> [Bug fix]Update teeu_xgboost.md

- docs/locales/zh_CN/LC_MESSAGES/tutorial/teeu/teeu_labelencoder.po
- docs/tutorial/index.rst
- docs/tutorial/teeu/teeu_labelencoder.md
> 【OSCP】为 TEEU 添加“标签编码”预处理教程

- .circleci/config.yml
- .circleci/continue-config.yml
- dev-requirements.txt
- requirements.txt
* Fixed various in ci pipeline
* Updated serving lib to latest
> Suppress no tests exit code

- tests/ml/nn/sl/attack/test_torch_lia.py
fix test_torch_lia as numpy upgraded
> fix test_torch_lia

- docker/release/secretflow-gpu.Dockerfile
- docs/getting_started/installation.md
1. update python version to 3.10
2. update jax version to 0.4.25
3. fix gpu dockerfile build error
> fix gpu docker install error

- secretflow/ml/nn/experimental/fl/backend/torch/strategy/fed_per.py
- secretflow/ml/nn/fl/backend/tensorflow/strategy/fed_avg_u.py
- secretflow/ml/nn/fl/backend/tensorflow/strategy/fed_avg_w.py
- secretflow/ml/nn/fl/backend/tensorflow/strategy/fed_prox.py
- secretflow/ml/nn/fl/backend/tensorflow/strategy/fed_scr.py
- secretflow/ml/nn/fl/backend/tensorflow/strategy/fed_stc.py
- secretflow/ml/nn/fl/backend/torch/fl_base.py
- secretflow/ml/nn/fl/backend/torch/strategy/fed_avg_w.py
- secretflow/ml/nn/fl/backend/torch/strategy/fed_prox.py
- secretflow/ml/nn/fl/backend/torch/strategy/scaffold.py
FL BN skip_bn在训练过程中没有正确识别并跳过，该pr修复该问题。
> fix get_weights in train step

- .circleci/release-config.yml
- docker/release/anolis-lite.Dockerfile
- docker/release/anolis.Dockerfile
- docker/release/build.sh
#修复docker buildx 语法问题
#修复构建nsjail镜像过程缺少gcc 问题
> #修复docker buildx 语法问题

- .circleci/release-config.yml
- docker/release/build.sh
* Update release-config.yml (#1291)
* fix dockerfiles (#1292)
* use docker buildx imagetools create instead of build
> Fix build scripts (#1294)

- docs/developer/benchmark/psi_benchmark.md
- docs/locales/zh_CN/LC_MESSAGES/developer/benchmark/psi_benchmark.po
> 修改psi benchmark文档中，生成数据的错误用法

- docs/developer/benchmark/psi_benchmark.md
Remove extra spaces in the table HTML code
> Remove extra spaces in the table HTML code

- docs/developer/benchmark/psi_benchmark.md
Fix an error in html table code
> Fix an error in html table code

- docs/developer/benchmark/psi_benchmark.md
Fix some incorrect data in PSI Benchmark
> Fix some incorrect data in PSI Benchmark

- secretflow/component/core/dist_data/report.py
- secretflow/version.py
- 修复分组统计无法展示report bug
- 更新版本号至1.10.0b1
> fix report and update version to 1.10.0b1

- secretflow_fl/ml/nn/fl/backend/torch/strategy/__init__.py
- secretflow_fl/ml/nn/fl/backend/torch/strategy/moon.py
- tests/ml/nn/fl/strategy/test_moon_torch.py
> OSCP任务：在 SecretFlow 中实现使用对比学习的联邦图像分类任务(#1001)
> 【OSCP】在 SecretFlow 中实现联邦学习策略 MOON(#1001)

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yaml
Remove blank template and fix feature request
> remove black template

- README.md
> Add good-first-issue badge and description

- docs/user_guide/preprocessing/WeightOfEvidenceEncoding.ipynb
1. WOE使用CompVDataFrame；
2. 在最后执行sf.shutdown()；
> 更新 woe doc

- docs/tutorial/data_preprocessing_with_data_frame.ipynb
- docs/user_guide/mpc_ml/feature_eng.ipynb
- docs/user_guide/preprocessing/WeightOfEvidenceEncoding.ipynb
1. WOE 使用 CompVDataFrame 演示；
2. 更新MinMaxScaler、OneHotEncoder、LabelEncoder、KBinsDiscretizer导入路径；
3. SSPValue使用新的接口；
4. 在最后执行sf.shutdown()；
> Update sf doc code

- CONTRIBUTING.md
- secretflow/data/horizontal/dataframe.py
Description
This fix results in a lack of pytest and other testing environments https://github.com/secretflow/secretflow/pull/1686
> fix pytest 

- docs/locales/zh_CN/LC_MESSAGES/tutorial/Federate_Learning_for_Image_Classification.po
- docs/tutorial/Federate_Learning_for_Image_Classification.ipynb
Resolves https://github.com/secretflow/secretflow/issues/1746
1. Verify the code implementation in `Federate_Learning_for_Image_Classification.ipynb` successfully
2. Refine the English version document of  `Federate_Learning_for_Image_Classification.ipynb`, including correction of translation based on Chinese version documents, for example
> Docs: refine the English version document of `Federate_Learning_for_Image_Classification.ipynb`

- examples/security/h_gia/GIAvMP_attack/GIAvMP_torch.py
- examples/security/h_gia/GIAvMP_attack/README.md
- examples/security/h_gia/GIAvMP_attack/utils.py
- tests/ml/nn/fl/attack/test_torch_GIAvMP.py
GIAvMP is an active gradient inversion attack, which poisons the local model of the victim party in FL to improve the attack performance.
> add new attack GIAvMP

- docs/locales/zh_CN/LC_MESSAGES/tutorial/Federated_Learning_with_Pytorch_backend.po
- docs/tutorial/Federated_Learning_with_Pytorch_backend.ipynb
Resolves #1747 
1. Verify the code implementation in **Federated_Learning_with_Pytorch_backend.ipynb** successfully.
2. Modify the content of **Federated_Learning_with_Pytorch_backend.ipynb** and the correspoding .po file, to make the content more fluent.
> docs: modify the content of Federated_Learning_with_Pytorch_backend.ipynb and the correspoding .po file

- docs/tutorial/Split_Learning_for_bank_marketing.ipynb
fix https://github.com/secretflow/secretflow/issues/1748
1. fix the  import path of `MinMaxScaler` and `LabelEncoder`
2. refine some English expression of tutorial
> fix: fix the import path of MinMaxScaler and LabelEncoder in secretflow version 1.11.0b1

- docs/user_guide/federated_learning/vertical_federated_learning/SplitRec/efficiency/sl_compressor.ipynb
> fix: fix the import path of MinMaxScaler and LabelEncoder in secretflow

- examples/app/h_cv/KLFedALA/ALAsys/ALA.py
- examples/app/h_cv/KLFedALA/ALAsys/fl/client.py
- examples/app/h_cv/KLFedALA/ALAsys/fl/models.py
- examples/app/h_cv/KLFedALA/ALAsys/fl/server.py
- examples/app/h_cv/KLFedALA/ALAsys/main.py
- examples/app/h_cv/KLFedALA/ALAsys/utilmodel/data_utils.py
- examples/app/h_cv/KLFedALA/README.md
> 在sf框架中基于KL散度优化FedALA算法

- secretflow_fl/ml/nn/sl/attacks/PGBA_torch.py
Description
Fixed #999  在 SecretFlow 中实现垂直联邦后门攻击 BadVFL-PKDD
> 【OSCP】 在 SecretFlow 中实现垂直联邦后门攻击 BadVFL-PKDD #999

- docs/tutorial/lr_with_spu.ipynb
Fixed https://github.com/secretflow/secretflow/issues/1872
删除引起报错的
```python
sf.shutdown()
```
并重新运行获得结果
> 【OSCP Docs】 验证文档「使用 SPU 进行逻辑回归」

- docs/tutorial/FedDataFrameDataLoader.ipynb
Fixed #1867
修改内容：
1. 修正了运行报错的wget命令
2. python版本更新为3.10
> 【OSCP Docs】验证文档「在SecretFlow中加载csv数据」 #1867
